# Generated by Django 5.0.4 on 2024-05-15 12:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utkal_Gym_app', '0003_alter_enrollment_enrollment_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('Attendance_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Selected_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('phone_Number', models.CharField(max_length=15)),
                ('log_in', models.CharField(max_length=100)),
                ('log_out', models.CharField(max_length=100)),
                ('Selected_workout', models.CharField(max_length=200)),
                ('trained_By', models.CharField(max_length=200)),
            ],
        ),
    ]
